#!/bin/zsh

killall -9 plusxome

PORT=3020

for base in tests/*(/) ; do
    echo for gdb: run --base-directory $base --config $base/config --port $PORT &
    ./bin/plusxome --base-directory $base --config $base/config --port $PORT &
    for t in $(ls $base | egrep '\.(t|sh)$' | sort -n) ; do
        case $t in
	    *.t)
	        curl -s http://localhost:$PORT$(head -1 $base/$t) > /tmp/runtests-$$-saw
	        sed -n '2,$ p' < $base/$t > /tmp/runtests-$$-wanted
	        echo ; echo $base/$t
	        if cmp -s /tmp/runtests-$$-{wanted,saw} ; then
	            echo " - passed"
	        else
		    F=/tmp/runtests-$$-$(basename $base)-$(basename $t .t)
		    cp -v /tmp/runtests-$$-saw $F
	            diff -u /tmp/runtests-$$-wanted $F
	        fi
		;;
	    *.sh)
		(cd $base ; ./$t)
		;;
	esac
    done
    kill %1
    PORT=$(expr $PORT + 1)
done
