#!/bin/zsh -e

for base in tests/*(/) ; do
    ./bin/plusxome --base-directory $base --config $base/config --port 3008 &
    for t in $base/*.t ; do
        curl -s http://localhost:3008$(head -1 $t) > /tmp/runtests-$$-saw
        sed -n '2,$ p' < $t > /tmp/runtests-$$-wanted
        echo ; echo $t
        if cmp -s /tmp/runtests-$$-{wanted,saw} ; then
            echo " - passed"
        else
            diff -u /tmp/runtests-$$-{wanted,saw}
        fi
    done
    kill %1
done
